language: node_js
node_js:
  - "node"
  - "10"
cache: yarn
install: yarn  
deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
services: mongodb  
addons:
  sonarcloud:
    organization: "nodulusteam-github" # the key of the org you chose at step #3  
before_script:
  - npm test 
script:
  - sonar-scanner  